#!/bin/bash

echo "==================================="
echo "Docker Desktop WSL2 Setup Guide"
echo "==================================="
echo ""
echo "To enable Docker in this WSL2 distro, please follow these steps:"
echo ""
echo "1. Open Docker Desktop on Windows"
echo "2. Click the Settings (gear) icon"
echo "3. Go to 'Resources' → 'WSL Integration'"
echo "4. Enable integration with your distro (should show your WSL distro name)"
echo "5. Click 'Apply & Restart'"
echo "6. Wait for Docker Desktop to restart"
echo ""
echo "After completing these steps, run this command to verify:"
echo "  docker --version"
echo ""
echo "Then navigate to the project and start the containers:"
echo "  cd /home/damian/YukonGroupApps/cabinet-quoting-system"
echo "  docker compose up -d"
echo ""
echo "To check if containers are running:"
echo "  docker compose ps"
echo ""
echo "==================================="
echo ""
echo "Alternative: If Docker Desktop is not available, you can:"
echo "1. Install Docker Engine directly in WSL2"
echo "2. Use the GitHub MCP tools to work with the repository"
echo ""